// ─── Styles ───────────────────────────────────────────────────────────────────

import { StyleSheet } from 'react-native';
import { Colors, Radius } from '@/constants/theme';
import { clampSp, clampDp } from './_utils';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: Colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    gap: clampDp(12, 8, 20),
  },
  loadingText: {
    color: Colors.textSecondary,
    fontSize: clampSp(14, 12, 16),
  },

  // ── Header ────────────────────────────────────────────────────────────────
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: clampDp(14, 10, 20),
    paddingHorizontal: clampDp(14, 10, 20),
    backgroundColor: Colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: Colors.surfaceBorder,
    gap: clampDp(8, 4, 12),
  },
  headerEdit: {
    borderBottomColor: Colors.warning + '80',
    borderBottomWidth: 2,
  },
  backBtn: {
    width: clampDp(40, 36, 48),
    height: clampDp(40, 36, 48),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.md,
    backgroundColor: Colors.surfaceElevated,
  },
  backIcon: {
    fontSize: clampSp(18, 16, 22),
    color: Colors.textPrimary,
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: clampSp(18, 16, 22),
    fontWeight: '800',
    color: Colors.textPrimary,
  },
  headerSub: {
    fontSize: clampSp(11, 10, 13),
    color: Colors.primary,
    fontWeight: '600',
    letterSpacing: 0.3,
    marginTop: 2,
  },
  headerSubEdit: {
    color: Colors.warning,
  },
  cartBtn: {
    width: clampDp(40, 36, 48),
    height: clampDp(40, 36, 48),
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  cartIcon: {
    fontSize: clampSp(22, 20, 26),
  },
  cartBadge: {
    position: 'absolute',
    top: 0,
    right: 0,
    backgroundColor: Colors.primary,
    borderRadius: Radius.full,
    width: clampDp(18, 16, 22),
    height: clampDp(18, 16, 22),
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartBadgeText: {
    fontSize: clampSp(9, 8, 11),
    fontWeight: '800',
    color: Colors.white,
  },

  editBanner: {
    backgroundColor: Colors.warning + '18',
    borderBottomWidth: 1,
    borderBottomColor: Colors.warning + '40',
    paddingHorizontal: clampDp(14, 10, 20),
    paddingVertical: clampDp(8, 6, 12),
  },
  editBannerText: {
    fontSize: clampSp(11, 10, 13),
    color: Colors.warning,
    fontWeight: '600',
    letterSpacing: 0.2,
  },

  // ── Category Tabs ──────────────────────────────────────────────────────────
  catRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: clampDp(12, 8, 20),
    paddingVertical: clampDp(10, 8, 14),
    gap: clampDp(8, 6, 12),
  },
  catBtn: {
    alignItems: 'center',
    paddingHorizontal: clampDp(14, 10, 20),
    paddingVertical: clampDp(8, 6, 12),
    borderRadius: Radius.lg,
    backgroundColor: Colors.surfaceElevated,
    borderWidth: 1,
    borderColor: Colors.surfaceBorder,
    gap: clampDp(3, 2, 5),
  },
  catBtnActive: {
    backgroundColor: Colors.primaryGlow,
    borderColor: Colors.primary,
  },
  catIcon: {
    fontSize: clampSp(18, 16, 22),
  },
  catLabel: {
    fontSize: clampSp(11, 10, 13),
    fontWeight: '600',
    color: Colors.textSecondary,
  },
  catLabelActive: {
    color: Colors.primary,
  },
  catRowWrapper: {
    backgroundColor: Colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: Colors.surfaceBorder,
    height: clampDp(74, 68, 84),
    justifyContent: 'center',
  },

  // ── Menu List ──────────────────────────────────────────────────────────────
  menuList: {
    padding: clampDp(12, 8, 20),
    gap: clampDp(10, 8, 14),
  },
  emptyCategory: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: clampDp(48, 32, 64),
    gap: clampDp(12, 8, 18),
  },
  emptyCategoryEmoji: {
    fontSize: clampSp(40, 32, 52),
  },
  emptyCategoryText: {
    fontSize: clampSp(14, 12, 16),
    color: Colors.textMuted,
    fontWeight: '600',
  },

  // ── Menu Card ─────────────────────────────────────────────────────────────
  menuCard: {
    flexDirection: 'row',
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: clampDp(14, 10, 20),
    borderWidth: 1,
    borderColor: Colors.surfaceBorder,
    alignItems: 'center',
    gap: clampDp(10, 8, 14),
  },
  menuCardDisabled: {
    opacity: 0.4,
  },
  menuCardLeft: {
    flex: 1,
  },
  menuCardRight: {
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: clampDp(88, 76, 110),
  },
  menuCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: clampDp(5, 4, 8),
    marginBottom: clampDp(4, 3, 6),
    flexWrap: 'wrap',
  },
  vegBadge: {
    width: clampDp(16, 14, 20),
    height: clampDp(16, 14, 20),
    borderRadius: 3,
    borderWidth: 1,
    borderColor: '#333',
    alignItems: 'center',
    justifyContent: 'center',
  },
  vegDot: {
    width: clampDp(8, 7, 10),
    height: clampDp(8, 7, 10),
    borderRadius: clampDp(4, 3, 5),
  },
  tagChip: {
    backgroundColor: Colors.primaryGlow,
    paddingHorizontal: clampDp(6, 5, 8),
    paddingVertical: clampDp(1, 1, 2),
    borderRadius: Radius.full,
  },
  tagText: {
    fontSize: clampSp(9, 8, 11),
    color: Colors.primary,
    fontWeight: '700',
  },
  // Hint badges shown on menu cards
  variantHintChip: {
    backgroundColor: '#1a2030',
    paddingHorizontal: clampDp(6, 5, 8),
    paddingVertical: clampDp(1, 1, 2),
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: '#334',
  },
  variantHintText: {
    fontSize: clampSp(9, 8, 11),
    color: '#8899cc',
    fontWeight: '700',
  },
  addonHintChip: {
    backgroundColor: '#201a30',
    paddingHorizontal: clampDp(6, 5, 8),
    paddingVertical: clampDp(1, 1, 2),
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: '#433',
  },
  addonHintText: {
    fontSize: clampSp(9, 8, 11),
    color: '#cc88aa',
    fontWeight: '700',
  },
  menuItemName: {
    fontSize: clampSp(14, 12, 17),
    fontWeight: '700',
    color: Colors.textPrimary,
    marginBottom: clampDp(2, 1, 4),
  },
  menuItemDesc: {
    fontSize: clampSp(11, 10, 13),
    color: Colors.textSecondary,
    lineHeight: clampSp(16, 14, 19),
    marginBottom: clampDp(5, 4, 8),
  },
  menuItemPrice: {
    fontSize: clampSp(14, 12, 17),
    fontWeight: '800',
    color: Colors.primary,
  },
  addBtn: {
    backgroundColor: Colors.surfaceElevated,
    borderRadius: Radius.md,
    paddingHorizontal: clampDp(14, 10, 20),
    paddingVertical: clampDp(10, 8, 14),
    borderWidth: 1.5,
    borderColor: Colors.surfaceBorder,
    alignItems: 'center',
  },
  addBtnText: {
    fontSize: clampSp(13, 12, 15),
    fontWeight: '700',
    color: Colors.textPrimary,
  },
  inlineStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.primaryGlow,
    borderRadius: Radius.md,
    borderWidth: 1.5,
    borderColor: Colors.primary,
    overflow: 'hidden',
  },
  stepperBtn: {
    width: clampDp(34, 30, 42),
    height: clampDp(38, 34, 46),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.surfaceElevated,
  },
  stepperBtnAdd: {
    backgroundColor: Colors.primary,
  },
  stepperBtnText: {
    fontSize: clampSp(18, 16, 22),
    fontWeight: '700',
    color: Colors.textPrimary,
    lineHeight: clampSp(22, 20, 26),
  },
  stepperBtnTextAdd: {
    color: Colors.white,
  },
  stepperCount: {
    fontSize: clampSp(15, 13, 18),
    fontWeight: '800',
    color: Colors.primary,
    minWidth: clampDp(28, 24, 36),
    textAlign: 'center',
  },
  unavailableChip: {
    backgroundColor: Colors.surfaceElevated,
    borderRadius: Radius.md,
    paddingHorizontal: clampDp(10, 8, 14),
    paddingVertical: clampDp(6, 5, 10),
  },
  unavailableText: {
    fontSize: clampSp(11, 10, 13),
    color: Colors.textMuted,
    fontWeight: '600',
  },

  // ── Bottom Bar ────────────────────────────────────────────────────────────
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: Colors.surface,
    borderTopWidth: 1,
    borderTopColor: Colors.surfaceBorder,
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: clampDp(12, 10, 18),
    paddingHorizontal: clampDp(14, 10, 20),
    gap: clampDp(10, 8, 16),
  },
  bottomBarLeft: {
    flex: 1,
  },
  bottomBarCount: {
    fontSize: clampSp(11, 10, 13),
    color: Colors.textSecondary,
    fontWeight: '600',
  },
  bottomBarTotal: {
    fontSize: clampSp(18, 16, 22),
    fontWeight: '800',
    color: Colors.textPrimary,
    marginTop: 2,
  },
  bottomBarRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: clampDp(8, 6, 12),
  },
  cartPreviewBtn: {
    backgroundColor: Colors.surfaceElevated,
    borderRadius: Radius.md,
    paddingHorizontal: clampDp(14, 10, 20),
    paddingVertical: clampDp(12, 10, 16),
    borderWidth: 1,
    borderColor: Colors.surfaceBorder,
  },
  cartPreviewBtnText: {
    fontSize: clampSp(13, 12, 15),
    fontWeight: '700',
    color: Colors.textSecondary,
  },
  saveBtn: {
    backgroundColor: Colors.primary,
    borderRadius: Radius.md,
    paddingHorizontal: clampDp(20, 16, 28),
    paddingVertical: clampDp(14, 12, 18),
    minWidth: clampDp(110, 90, 140),
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveBtnDisabled: {
    opacity: 0.6,
  },
  saveBtnText: {
    color: Colors.white,
    fontSize: clampSp(14, 13, 16),
    fontWeight: '700',
  },
  cartSaveBtn: {
    marginHorizontal: clampDp(14, 10, 20),
    marginTop: clampDp(8, 6, 12),
    marginBottom: clampDp(4, 2, 8),
  },

  // ── Shared Modal Base ─────────────────────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'flex-end',
  },
  cartModal: {
    backgroundColor: Colors.surface,
    borderTopLeftRadius: clampDp(24, 18, 32),
    borderTopRightRadius: clampDp(24, 18, 32),
    borderTopWidth: 1,
    borderColor: Colors.surfaceBorder,
  },
  cartModalHandle: {
    width: clampDp(36, 28, 48),
    height: clampDp(4, 3, 6),
    backgroundColor: Colors.surfaceBorder,
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: clampDp(10, 8, 14),
    marginBottom: clampDp(4, 2, 6),
  },
  cartModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: clampDp(14, 10, 20),
    borderBottomWidth: 1,
    borderBottomColor: Colors.surfaceBorder,
  },
  cartModalTitle: {
    fontSize: clampSp(18, 16, 22),
    fontWeight: '700',
    color: Colors.textPrimary,
  },
  cartModalCount: {
    fontSize: clampSp(14, 12, 16),
    fontWeight: '500',
    color: Colors.textSecondary,
  },
  cartModalClose: {
    fontSize: clampSp(16, 14, 18),
    color: Colors.textSecondary,
    padding: clampDp(4, 3, 6),
  },

  // ── Variant / Addon Picker Modal ──────────────────────────────────────────
  pickerModal: {
    backgroundColor: Colors.surface,
    borderTopLeftRadius: clampDp(24, 18, 32),
    borderTopRightRadius: clampDp(24, 18, 32),
    borderTopWidth: 1,
    borderColor: Colors.surfaceBorder,
  },
  pickerSubtitle: {
    fontSize: clampSp(11, 10, 13),
    color: Colors.textSecondary,
    marginTop: 3,
  },
  pickerSection: {
    paddingHorizontal: clampDp(14, 10, 20),
    paddingTop: clampDp(16, 12, 22),
  },
  pickerSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: clampDp(8, 6, 12),
    marginBottom: clampDp(10, 8, 14),
  },
  pickerSectionTitle: {
    fontSize: clampSp(13, 12, 15),
    fontWeight: '800',
    color: Colors.textPrimary,
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  requiredChip: {
    backgroundColor: '#2a1a1a',
    paddingHorizontal: clampDp(8, 6, 10),
    paddingVertical: clampDp(2, 1, 4),
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: Colors.error + '60',
  },
  requiredChipText: {
    fontSize: clampSp(10, 9, 12),
    color: Colors.error,
    fontWeight: '700',
  },
  optionalChip: {
    backgroundColor: Colors.surfaceElevated,
    paddingHorizontal: clampDp(8, 6, 10),
    paddingVertical: clampDp(2, 1, 4),
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: Colors.surfaceBorder,
  },
  optionalChipText: {
    fontSize: clampSp(10, 9, 12),
    color: Colors.textMuted,
    fontWeight: '700',
  },
  pickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: clampDp(12, 10, 16),
    paddingVertical: clampDp(12, 10, 16),
    paddingHorizontal: clampDp(12, 10, 16),
    borderRadius: Radius.md,
    marginBottom: clampDp(6, 4, 10),
    backgroundColor: Colors.surfaceElevated,
    borderWidth: 1.5,
    borderColor: Colors.surfaceBorder,
  },
  pickerRowSelected: {
    backgroundColor: Colors.primaryGlow,
    borderColor: Colors.primary,
  },
  pickerRowName: {
    flex: 1,
    fontSize: clampSp(14, 12, 16),
    fontWeight: '600',
    color: Colors.textSecondary,
  },
  pickerRowNameSelected: {
    color: Colors.textPrimary,
    fontWeight: '700',
  },
  pickerRowPrice: {
    fontSize: clampSp(14, 12, 16),
    fontWeight: '700',
    color: Colors.textMuted,
  },
  pickerRowPriceSelected: {
    color: Colors.primary,
  },
  // Radio button (for variants — single select)
  radioOuter: {
    width: clampDp(20, 18, 24),
    height: clampDp(20, 18, 24),
    borderRadius: clampDp(10, 9, 12),
    borderWidth: 2,
    borderColor: Colors.surfaceBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioOuterSelected: {
    borderColor: Colors.primary,
  },
  radioInner: {
    width: clampDp(10, 9, 12),
    height: clampDp(10, 9, 12),
    borderRadius: clampDp(5, 4, 6),
    backgroundColor: Colors.primary,
  },
  // Checkbox (for addons — multi select)
  checkboxOuter: {
    width: clampDp(20, 18, 24),
    height: clampDp(20, 18, 24),
    borderRadius: clampDp(4, 3, 6),
    borderWidth: 2,
    borderColor: Colors.surfaceBorder,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.surfaceElevated,
  },
  checkboxOuterSelected: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primary,
  },
  checkboxTick: {
    fontSize: clampSp(12, 10, 14),
    color: Colors.white,
    fontWeight: '800',
    lineHeight: clampSp(14, 12, 16),
  },
  // Confirm button at bottom of picker
  pickerConfirmBtn: {
    position: 'absolute',
    bottom: clampDp(16, 12, 24),
    left: clampDp(14, 10, 20),
    right: clampDp(14, 10, 20),
    backgroundColor: Colors.primary,
    borderRadius: Radius.md,
    paddingVertical: clampDp(16, 14, 20),
    paddingHorizontal: clampDp(20, 16, 28),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pickerConfirmText: {
    fontSize: clampSp(15, 13, 17),
    fontWeight: '700',
    color: Colors.white,
  },
  pickerConfirmPrice: {
    fontSize: clampSp(15, 13, 17),
    fontWeight: '800',
    color: Colors.white,
  },

  // ── Cart entries ──────────────────────────────────────────────────────────
  cartEmptyText: {
    textAlign: 'center',
    color: Colors.textMuted,
    padding: clampDp(32, 24, 48),
    fontSize: clampSp(14, 12, 16),
  },
  cartEntry: {
    padding: clampDp(14, 10, 20),
    borderBottomWidth: 1,
    borderBottomColor: Colors.surfaceBorder,
    gap: clampDp(8, 6, 12),
  },
  cartEntryTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: clampDp(8, 6, 12),
  },
  cartEntryName: {
    fontSize: clampSp(14, 12, 16),
    fontWeight: '600',
    color: Colors.textPrimary,
  },
  cartEntrySubtitle: {
    fontSize: clampSp(11, 10, 13),
    color: Colors.textSecondary,
    marginTop: clampDp(2, 1, 4),
    fontStyle: 'italic',
  },
  cartEntryPrice: {
    fontSize: clampSp(14, 12, 16),
    fontWeight: '700',
    color: Colors.primary,
  },
  cartEntryActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: clampDp(8, 6, 12),
  },
  cartEntryNote: {
    fontSize: clampSp(11, 10, 13),
    color: Colors.textMuted,
    fontStyle: 'italic',
    marginTop: clampDp(2, 1, 4),
  },
  qtyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: clampDp(8, 6, 12),
    backgroundColor: Colors.surfaceElevated,
    borderRadius: Radius.md,
    padding: clampDp(4, 3, 6),
  },
  qtyBtn: {
    width: clampDp(30, 26, 38),
    height: clampDp(30, 26, 38),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.surfaceBorder,
    borderRadius: clampDp(6, 5, 8),
  },
  qtyBtnText: {
    fontSize: clampSp(16, 14, 20),
    color: Colors.textPrimary,
    fontWeight: '700',
    lineHeight: clampSp(20, 18, 24),
  },
  qtyValue: {
    fontSize: clampSp(14, 12, 16),
    fontWeight: '700',
    color: Colors.textPrimary,
    minWidth: clampDp(20, 16, 28),
    textAlign: 'center',
  },
  noteBtn: {
    flex: 1,
    backgroundColor: Colors.surfaceElevated,
    borderRadius: Radius.sm,
    paddingHorizontal: clampDp(8, 6, 12),
    paddingVertical: clampDp(8, 6, 12),
    borderWidth: 1,
    borderColor: Colors.surfaceBorder,
  },
  noteBtnText: {
    fontSize: clampSp(11, 10, 13),
    color: Colors.textSecondary,
  },
  removeBtn: {
    padding: clampDp(4, 3, 6),
  },
  removeBtnText: {
    fontSize: clampSp(18, 16, 22),
  },
  specialBox: {
    padding: clampDp(14, 10, 20),
    borderBottomWidth: 1,
    borderBottomColor: Colors.surfaceBorder,
    backgroundColor: Colors.surfaceElevated,
    gap: clampDp(8, 6, 12),
  },
  specialLabel: {
    fontSize: clampSp(12, 11, 14),
    fontWeight: '700',
    color: Colors.warning,
    letterSpacing: 0.5,
  },
  specialInput: {
    backgroundColor: Colors.surface,
    borderRadius: Radius.md,
    padding: clampDp(10, 8, 14),
    fontSize: clampSp(13, 12, 15),
    color: Colors.textPrimary,
    borderWidth: 1,
    borderColor: Colors.surfaceBorder,
    minHeight: clampDp(70, 60, 90),
    textAlignVertical: 'top',
  },
  cartTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: clampDp(14, 10, 20),
  },
  cartTotalLabel: {
    fontSize: clampSp(16, 14, 19),
    fontWeight: '700',
    color: Colors.textSecondary,
  },
  cartTotalSub: {
    fontSize: clampSp(11, 10, 13),
    color: Colors.textMuted,
    marginTop: 2,
  },
  cartTotalValue: {
    fontSize: clampSp(22, 18, 28),
    fontWeight: '800',
    color: Colors.primary,
  },

  // ── Note Modal ────────────────────────────────────────────────────────────
  noteOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    padding: clampDp(20, 16, 32),
  },
  noteModal: {
    backgroundColor: Colors.surface,
    borderRadius: Radius.xl,
    padding: clampDp(20, 16, 28),
    borderWidth: 1,
    borderColor: Colors.surfaceBorder,
    gap: clampDp(8, 6, 12),
  },
  noteModalTitle: {
    fontSize: clampSp(16, 14, 19),
    fontWeight: '700',
    color: Colors.textPrimary,
  },
  noteModalSub: {
    fontSize: clampSp(12, 11, 14),
    color: Colors.textSecondary,
  },
  noteInput: {
    backgroundColor: Colors.surfaceElevated,
    borderRadius: Radius.md,
    padding: clampDp(12, 10, 16),
    fontSize: clampSp(14, 12, 16),
    color: Colors.textPrimary,
    borderWidth: 1.5,
    borderColor: Colors.surfaceBorder,
    minHeight: clampDp(80, 70, 100),
    textAlignVertical: 'top',
    marginTop: clampDp(4, 2, 8),
  },
  noteModalBtns: {
    flexDirection: 'row',
    gap: clampDp(10, 8, 14),
    marginTop: clampDp(4, 2, 8),
  },
  noteCancelBtn: {
    flex: 1,
    padding: clampDp(14, 12, 18),
    borderRadius: Radius.md,
    backgroundColor: Colors.surfaceElevated,
    alignItems: 'center',
  },
  noteCancelText: {
    fontSize: clampSp(14, 13, 16),
    fontWeight: '600',
    color: Colors.textSecondary,
  },
  noteSaveBtn: {
    flex: 1,
    padding: clampDp(14, 12, 18),
    borderRadius: Radius.md,
    backgroundColor: Colors.primary,
    alignItems: 'center',
  },
  noteSaveText: {
    fontSize: clampSp(14, 13, 16),
    fontWeight: '700',
    color: Colors.white,
  },

  // ── Exit Confirm ──────────────────────────────────────────────────────────
  confirmOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.75)',
    justifyContent: 'center',
    padding: clampDp(24, 18, 36),
  },
  confirmModal: {
    backgroundColor: Colors.surface,
    borderRadius: Radius.xl,
    padding: clampDp(20, 16, 28),
    borderWidth: 1,
    borderColor: Colors.surfaceBorder,
    gap: clampDp(8, 6, 12),
  },
  confirmTitle: {
    fontSize: clampSp(18, 16, 22),
    fontWeight: '800',
    color: Colors.textPrimary,
  },
  confirmBody: {
    fontSize: clampSp(13, 12, 15),
    color: Colors.textSecondary,
    lineHeight: clampSp(20, 18, 24),
  },
  confirmBtns: {
    flexDirection: 'row',
    gap: clampDp(10, 8, 14),
    marginTop: clampDp(8, 6, 12),
  },
  confirmCancel: {
    flex: 1,
    padding: clampDp(14, 12, 18),
    borderRadius: Radius.md,
    backgroundColor: Colors.primaryGlow,
    borderWidth: 1,
    borderColor: Colors.primary,
    alignItems: 'center',
  },
  confirmCancelText: {
    fontSize: clampSp(14, 13, 16),
    fontWeight: '700',
    color: Colors.primary,
  },
  confirmDiscard: {
    flex: 1,
    padding: clampDp(14, 12, 18),
    borderRadius: Radius.md,
    backgroundColor: '#2a1a1a',
    borderWidth: 1,
    borderColor: Colors.error,
    alignItems: 'center',
  },
  confirmDiscardText: {
    fontSize: clampSp(14, 13, 16),
    fontWeight: '700',
    color: Colors.error,
  },
});